name: cdairport-flightinfo-ci

env:
  DOCKERHUB_TAG: "noahziheng/jellyfin"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_TAG }}:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.DOCKERHUB_TAG }}:latest
          cache-to: type=inline

      - name: Image digests
        run: |
          echo image digest: ${{ steps.docker_build.outputs.digest }}
        

